apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- configmap.yaml
- deployment.yaml
- pvc.yaml

images:
- name: sarah-bot
  newName: localhost:5000/sarah-bot
  newTag: latest