name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:

    - name: checkout the repo
      uses: actions/checkout@v4

    - name: ghcr login
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN}}

    - name: get current time
      id: get_time
      run: echo "TIME=$(date +%s)" >> $GITHUB_OUTPUT
    
    - name: build and push the Docker image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ghcr.io/${{ github.actor }}/sarahbot:${{ steps.get_time.outputs.TIME }},ghcr.io/${{ github.actor }}/sarahbot:latest
